### PR TITLE
Update .gitignore and add support for depthwise separable convolutions

### PR DESCRIPTION
**Pull request by tehtea**
Hi Jin, I took your advice and will split up the original PR into smaller commits (and thus PRs) so its easier for you to review as well, let me know what you think about this one.

### CODE REVIEW

**Comment by jiny2001** [comment]
Thank you so much! I tested and it looks good. This is so nice!

Is this possible you upload the model if you have already trained model with the new option?
Also is this possible you add an explanation and put your credit about depth wise separable CNN to readme?

**Comment by tehtea** [comment]
No problem! :) I will upload the model and put my credit in due course (need to crunch some numbers with the frozen model first though)

**Comment by tehtea** [comment]
@jiny2001 Oh yeah, I'm not really sure if I did the calculation for the complexity of the depthwise separable layer correctly, is there a resource I can refer to find out what's the formula for calculating the complexity of a deep learning layer?

**Comment by jiny2001** [comment]
Hi, usually we calculate any multiplication/division as 1 and any addition/subtraction as 1. And also it should be pixel-wise. Input image size doesn't matter.

For example, if it's 3x3 CNN and input channel num is c1 and output channel num is c2, CNN part should be 3x3xc1xc2 and bias part should be c2 = 3x3xc1xc2 + c2

**Pull request merged**
